# Generated by Django 5.1.2 on 2024-12-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_attendance_check_in_alter_attendance_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
