# Generated by Django 5.1.2 on 2024-12-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='national_code',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
