# Generated by Django 5.1.2 on 2024-12-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
